### PR TITLE
First Pass at Demo App

### PR DESCRIPTION
**Pull request by samgreen**
- [Podfile](https://github.com/berbix/ios-toolkit-demo/pull/1/files#diff-8f7d6adf31268a2d897ee34bd170592648d6e520aa237104395e4a4438af50cb) is pretty typical for a Berbix integration (using the same custom specs repo)
- Heavy lifting happens in the [SessionViewController](https://github.com/berbix/ios-toolkit-demo/pull/1/files#diff-1bdf09917b6fc57776d43926e368741e091ca740b60b0b243dc4c4525bc02c8e)
- Navigation and view layout are mostly in storyboard with a few hand crafted AutoLayout examples
- Pod is committed and pre-installed so developers can download this repo and run in Xcode without CocoaPods
- Pod contains 2 frameworks (1 device & 1 simulator). The simulator framework contains both arm64 (for M1) and x86_64 (for Intel Mac)

# Remaining
- [ ] Custom README for this repo

### CODE REVIEW

**Comment by benbeltzer** [comment]
Looking through this now, but one thing is that I think the .gitignore needs to be updated. The `Pods/` is checked in currently

**Comment by samgreen** [comment]
> Looking through this now, but one thing is that I think the .gitignore needs to be updated. The `Pods/` is checked in currently

This is intentional. Referenced in the description.

**Comment by benbeltzer** [comment]
> This is intentional. Referenced in the description.

ah 🤦‍♂️  my bad

**Comment by samgreen** [comment]
More info on Pods/ approaches:

**Should I check the Pods directory into source control?**

https://guides.cocoapods.org/using/using-cocoapods.html

**Review by benbeltzer — APPROVED** [review]
I am not able to run locally due to xcode / device issues, but code looks good. Would be great to get @Shounak's eyes on it too

**Review by Shounak — APPROVED** [review]
App works great! Code looks good to me as well
image

**Pull request merged**
